from .MCS import MCS_Task
from .TSP import TSP_Task
from .GED import GED_Task
from .MCP import MCP_Task
from .MVC import MVC_Task
from .MIS import MIS_Task
from .Connected import Connected_Task
from .Diameter import Diameter_Task
from .Neighbor import Neighbor_Task
from .Distance import Distance_Task